/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.bytecare.assistenciatecnica.turma472.telas;

import apps.controller.userController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author andmi
 */
public class telaUsers extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaUsers
     */
    public telaUsers() {
        initComponents();
    }

    userController user = new userController(this);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idUser = new javax.swing.JLabel();
        campoUserId = new javax.swing.JTextField();
        nomeUser = new javax.swing.JLabel();
        campoNomeUser = new javax.swing.JTextField();
        foneUser = new javax.swing.JLabel();
        campoFoneUser = new javax.swing.JTextField();
        senhaUser = new javax.swing.JLabel();
        campoSenhaUser = new javax.swing.JTextField();
        loginUser = new javax.swing.JLabel();
        campoLoginUser = new javax.swing.JTextField();
        perfilUser = new javax.swing.JLabel();
        campoPerfilUser = new javax.swing.JComboBox<>();
        editUser = new javax.swing.JButton();
        removeUser = new javax.swing.JButton();
        addUser = new javax.swing.JButton();
        pesquisarUser = new javax.swing.JButton();

        setTitle("TechAssist v0.2 - Cadastro de Usuario");
        setMinimumSize(new java.awt.Dimension(575, 410));
        setPreferredSize(new java.awt.Dimension(575, 410));

        idUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        idUser.setText("* Id");
        idUser.setPreferredSize(new java.awt.Dimension(64, 32));

        campoUserId.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoUserId.setEnabled(false);
        campoUserId.setPreferredSize(null);
        campoUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUserIdActionPerformed(evt);
            }
        });

        nomeUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nomeUser.setText("* Nome");
        nomeUser.setMinimumSize(new java.awt.Dimension(100, 200));
        nomeUser.setPreferredSize(new java.awt.Dimension(100, 32));

        campoNomeUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoNomeUser.setMinimumSize(new java.awt.Dimension(100, 200));
        campoNomeUser.setPreferredSize(null);
        campoNomeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeUserActionPerformed(evt);
            }
        });

        foneUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        foneUser.setText("Fone");
        foneUser.setMaximumSize(new java.awt.Dimension(100, 32));
        foneUser.setMinimumSize(new java.awt.Dimension(100, 32));
        foneUser.setName(""); // NOI18N
        foneUser.setPreferredSize(new java.awt.Dimension(100, 32));

        campoFoneUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoFoneUser.setMinimumSize(new java.awt.Dimension(100, 200));
        campoFoneUser.setPreferredSize(null);
        campoFoneUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFoneUserActionPerformed(evt);
            }
        });

        senhaUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        senhaUser.setText("* Senha");
        senhaUser.setMaximumSize(new java.awt.Dimension(100, 32));
        senhaUser.setMinimumSize(new java.awt.Dimension(100, 32));
        senhaUser.setName(""); // NOI18N
        senhaUser.setPreferredSize(new java.awt.Dimension(100, 32));

        campoSenhaUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoSenhaUser.setMinimumSize(new java.awt.Dimension(100, 200));
        campoSenhaUser.setPreferredSize(null);
        campoSenhaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaUserActionPerformed(evt);
            }
        });

        loginUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        loginUser.setText("* Login");
        loginUser.setMaximumSize(new java.awt.Dimension(100, 32));
        loginUser.setMinimumSize(new java.awt.Dimension(100, 32));
        loginUser.setName(""); // NOI18N
        loginUser.setPreferredSize(new java.awt.Dimension(100, 32));

        campoLoginUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoLoginUser.setPreferredSize(null);
        campoLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginUserActionPerformed(evt);
            }
        });

        perfilUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        perfilUser.setText("* Perfil");
        perfilUser.setMaximumSize(new java.awt.Dimension(100, 32));
        perfilUser.setMinimumSize(new java.awt.Dimension(100, 32));
        perfilUser.setName(""); // NOI18N
        perfilUser.setPreferredSize(new java.awt.Dimension(100, 32));

        campoPerfilUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoPerfilUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        campoPerfilUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPerfilUserActionPerformed(evt);
            }
        });

        editUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/telas/iconeEditar.png"))); // NOI18N
        editUser.setMaximumSize(new java.awt.Dimension(70, 70));
        editUser.setMinimumSize(new java.awt.Dimension(70, 70));
        editUser.setPreferredSize(new java.awt.Dimension(70, 70));
        editUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserActionPerformed(evt);
            }
        });

        removeUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/telas/iconeRemover.png"))); // NOI18N
        removeUser.setMaximumSize(new java.awt.Dimension(70, 70));
        removeUser.setMinimumSize(new java.awt.Dimension(70, 70));
        removeUser.setPreferredSize(new java.awt.Dimension(70, 70));
        removeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUserActionPerformed(evt);
            }
        });

        addUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/telas/iconeAdd.png"))); // NOI18N
        addUser.setMaximumSize(new java.awt.Dimension(70, 70));
        addUser.setMinimumSize(new java.awt.Dimension(70, 70));
        addUser.setPreferredSize(new java.awt.Dimension(70, 70));
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });

        pesquisarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/icons/iconePesquisa.png"))); // NOI18N
        pesquisarUser.setMaximumSize(new java.awt.Dimension(70, 70));
        pesquisarUser.setMinimumSize(new java.awt.Dimension(70, 70));
        pesquisarUser.setPreferredSize(new java.awt.Dimension(70, 70));
        pesquisarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(campoUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(foneUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(senhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoFoneUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(addUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foneUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFoneUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(removeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeUserActionPerformed

    private void campoFoneUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFoneUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFoneUserActionPerformed

    private void campoSenhaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaUserActionPerformed

    private void campoLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginUserActionPerformed

    private void campoPerfilUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPerfilUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPerfilUserActionPerformed

    private void campoUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUserIdActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        try {
            user.addUser();
        } catch (SQLException ex) {
            Logger.getLogger(telaUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addUserActionPerformed

    private void pesquisarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarUserActionPerformed
        try {
            user.pesquisarUser();
        } catch (SQLException ex) {
            Logger.getLogger(telaUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pesquisarUserActionPerformed

    private void editUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserActionPerformed
        try {
            user.editUser();
        } catch (SQLException ex) {
            Logger.getLogger(telaUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editUserActionPerformed

    private void removeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUserActionPerformed
        user.removeUser();
    }//GEN-LAST:event_removeUserActionPerformed

    public JButton getAddUser() {
        return addUser;
    }

    public void setAddUser(JButton addUser) {
        this.addUser = addUser;
    }

    public JTextField getCampoFoneUser() {
        return campoFoneUser;
    }

    public void setCampoFoneUser(JTextField campoFoneUser) {
        this.campoFoneUser = campoFoneUser;
    }

    public JTextField getCampoLoginUser() {
        return campoLoginUser;
    }

    public void setCampoLoginUser(JTextField campoLoginUser) {
        this.campoLoginUser = campoLoginUser;
    }

    public JTextField getCampoNomeUser() {
        return campoNomeUser;
    }

    public void setCampoNomeUser(JTextField campoNomeUser) {
        this.campoNomeUser = campoNomeUser;
    }

    public JComboBox<String> getCampoPerfilUser() {
        return campoPerfilUser;
    }

    public void setCampoPerfilUser(JComboBox<String> campoPerfilUser) {
        this.campoPerfilUser = campoPerfilUser;
    }

    public JTextField getCampoSenhaUser() {
        return campoSenhaUser;
    }

    public void setCampoSenhaUser(JTextField campoSenhaUser) {
        this.campoSenhaUser = campoSenhaUser;
    }

    public JButton getEditUser() {
        return editUser;
    }

    public void setEditUser(JButton editUser) {
        this.editUser = editUser;
    }

    public JButton getRemoveUser() {
        return removeUser;
    }

    public void setRemoveUser(JButton removeUser) {
        this.removeUser = removeUser;
    }

    public JTextField getCampoUserId() {
        return campoUserId;
    }

    public void setCampoUserId(JTextField campoUserId) {
        this.campoUserId = campoUserId;
    }

    public JButton getPesquisarUser() {
        return pesquisarUser;
    }

    public void setPesquisarUser(JButton pesquisarUser) {
        this.pesquisarUser = pesquisarUser;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUser;
    private javax.swing.JTextField campoFoneUser;
    private javax.swing.JTextField campoLoginUser;
    private javax.swing.JTextField campoNomeUser;
    private javax.swing.JComboBox<String> campoPerfilUser;
    private javax.swing.JTextField campoSenhaUser;
    private javax.swing.JTextField campoUserId;
    private javax.swing.JButton editUser;
    private javax.swing.JLabel foneUser;
    private javax.swing.JLabel idUser;
    private javax.swing.JLabel loginUser;
    private javax.swing.JLabel nomeUser;
    private javax.swing.JLabel perfilUser;
    private javax.swing.JButton pesquisarUser;
    private javax.swing.JButton removeUser;
    private javax.swing.JLabel senhaUser;
    // End of variables declaration//GEN-END:variables
}
