/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.bytecare.assistenciatecnica.turma472.telas;

import apps.controller.clientesController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author andmi
 */
public class telaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaaCliente
     */
    public telaCliente() {
        initComponents();
    }
    
    clientesController cont = new clientesController(this);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoPesquisarCli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnRemoveCliente = new javax.swing.JButton();
        btnEditCliente = new javax.swing.JButton();
        btnAddClient = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoNomeCli = new javax.swing.JTextField();
        campoEnderCli = new javax.swing.JTextField();
        campoFoneCli = new javax.swing.JTextField();
        campoEmailCli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("TechAssist v0.3 - Cadastro de Clientes");
        setMaximumSize(new java.awt.Dimension(1014, 728));
        setMinimumSize(new java.awt.Dimension(1014, 728));
        setPreferredSize(new java.awt.Dimension(1014, 728));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        campoPesquisarCli.setToolTipText("digite um nome");
        campoPesquisarCli.setMaximumSize(new java.awt.Dimension(350, 35));
        campoPesquisarCli.setMinimumSize(new java.awt.Dimension(350, 35));
        campoPesquisarCli.setPreferredSize(new java.awt.Dimension(350, 35));
        campoPesquisarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisarCliActionPerformed(evt);
            }
        });
        campoPesquisarCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPesquisarCliKeyReleased(evt);
            }
        });

        tabelaClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaClientes.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "nome", "endereço", "fone", "email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaClientes.setRowHeight(25);
        tabelaClientes.setShowGrid(true);
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setText("Campos obrigatórios*");

        btnRemoveCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/telas/iconeRemover.png"))); // NOI18N
        btnRemoveCliente.setEnabled(false);
        btnRemoveCliente.setMaximumSize(new java.awt.Dimension(85, 85));
        btnRemoveCliente.setMinimumSize(new java.awt.Dimension(85, 85));
        btnRemoveCliente.setPreferredSize(new java.awt.Dimension(85, 85));
        btnRemoveCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveClienteActionPerformed(evt);
            }
        });

        btnEditCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/telas/iconeEditar.png"))); // NOI18N
        btnEditCliente.setEnabled(false);
        btnEditCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditCliente.setMaximumSize(new java.awt.Dimension(85, 85));
        btnEditCliente.setMinimumSize(new java.awt.Dimension(85, 85));
        btnEditCliente.setPreferredSize(new java.awt.Dimension(85, 85));
        btnEditCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClienteActionPerformed(evt);
            }
        });

        btnAddClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/telas/iconeAdd.png"))); // NOI18N
        btnAddClient.setMaximumSize(new java.awt.Dimension(85, 85));
        btnAddClient.setMinimumSize(new java.awt.Dimension(85, 85));
        btnAddClient.setPreferredSize(new java.awt.Dimension(85, 85));
        btnAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Nome*");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setText("Endereço");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Telefone*");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Email");

        campoNomeCli.setMaximumSize(new java.awt.Dimension(350, 35));
        campoNomeCli.setMinimumSize(new java.awt.Dimension(350, 35));
        campoNomeCli.setPreferredSize(new java.awt.Dimension(350, 35));
        campoNomeCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeCliActionPerformed(evt);
            }
        });

        campoEnderCli.setMaximumSize(new java.awt.Dimension(350, 35));
        campoEnderCli.setMinimumSize(new java.awt.Dimension(350, 35));
        campoEnderCli.setPreferredSize(new java.awt.Dimension(350, 35));

        campoFoneCli.setMaximumSize(new java.awt.Dimension(350, 35));
        campoFoneCli.setMinimumSize(new java.awt.Dimension(350, 35));
        campoFoneCli.setPreferredSize(new java.awt.Dimension(350, 35));

        campoEmailCli.setMaximumSize(new java.awt.Dimension(350, 35));
        campoEmailCli.setMinimumSize(new java.awt.Dimension(350, 35));
        campoEmailCli.setPreferredSize(new java.awt.Dimension(350, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/icons/iconeBusca.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoPesquisarCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(296, 296, 296)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(50, 50, 50))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoEnderCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(campoNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addGap(1, 1, 1))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(66, 66, 66))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoEmailCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(campoFoneCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(434, 434, 434))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(btnAddClient, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(323, 323, 323)))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoPesquisarCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(campoNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(campoEnderCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(campoFoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(campoEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAddClient, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(btnEditCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeCliActionPerformed

    private void campoPesquisarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisarCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesquisarCliActionPerformed

    private void btnAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientActionPerformed
        cont.addCliente();
        cont.limparCampos();
    }//GEN-LAST:event_btnAddClientActionPerformed

    private void btnRemoveClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveClienteActionPerformed
        cont.removeUser();
        cont.limparCampos();
    }//GEN-LAST:event_btnRemoveClienteActionPerformed

    private void btnEditClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClienteActionPerformed
        try {
            cont.editCliente();
        } catch (SQLException ex) {
            Logger.getLogger(telaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditClienteActionPerformed

    private void campoPesquisarCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisarCliKeyReleased
        cont.pesquisarClientes();
    }//GEN-LAST:event_campoPesquisarCliKeyReleased

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        cont.setarCampos();
    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        btnEditCliente.setEnabled(false);
        btnRemoveCliente.setEnabled(false);
        btnAddClient.setEnabled(true);
        tabelaClientes.setAutoResizeMode(WIDTH);
    }//GEN-LAST:event_formInternalFrameOpened

    public JButton getBtnAddClient() {
        return btnAddClient;
    }

    public void setBtnAddClient(JButton btnAddClient) {
        this.btnAddClient = btnAddClient;
    }

    public JButton getBtnEditCliente() {
        return btnEditCliente;
    }

    public void setBtnEditCliente(JButton btnEditCliente) {
        this.btnEditCliente = btnEditCliente;
    }

    public JButton getBtnRemoveCliente() {
        return btnRemoveCliente;
    }

    public void setBtnRemoveCliente(JButton btnRemoveCliente) {
        this.btnRemoveCliente = btnRemoveCliente;
    }

    public JTextField getCampoEmailCli() {
        return campoEmailCli;
    }

    public void setCampoEmailCli(JTextField campoEmailCli) {
        this.campoEmailCli = campoEmailCli;
    }

    public JTextField getCampoEnderCli() {
        return campoEnderCli;
    }

    public void setCampoEnderCli(JTextField campoEnderCli) {
        this.campoEnderCli = campoEnderCli;
    }

    public JTextField getCampoFoneCli() {
        return campoFoneCli;
    }

    public void setCampoFoneCli(JTextField campoFoneCli) {
        this.campoFoneCli = campoFoneCli;
    }

    public JTextField getCampoNomeCli() {
        return campoNomeCli;
    }

    public void setCampoNomeCli(JTextField campoNomeCli) {
        this.campoNomeCli = campoNomeCli;
    }

    public JTextField getCampoPesquisarCli() {
        return campoPesquisarCli;
    }

    public void setCampoPesquisarCli(JTextField campoPesquisarCli) {
        this.campoPesquisarCli = campoPesquisarCli;
    }

    public JTable getTabelaClientes() {
        return tabelaClientes;
    }

    public void setTabelaClientes(JTable tabelaClientes) {
        this.tabelaClientes = tabelaClientes;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClient;
    private javax.swing.JButton btnEditCliente;
    private javax.swing.JButton btnRemoveCliente;
    private javax.swing.JTextField campoEmailCli;
    private javax.swing.JTextField campoEnderCli;
    private javax.swing.JTextField campoFoneCli;
    private javax.swing.JTextField campoNomeCli;
    private javax.swing.JTextField campoPesquisarCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaClientes;
    // End of variables declaration//GEN-END:variables
}
