/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.bytecare.assistenciatecnica.turma472.telas;
import java.awt.*;
import javax.swing.*;
import br.com.bytecare.assistenciatecnica.turma472.telas.*;
import java.beans.PropertyVetoException;
import java.text.DateFormat;
import java.util.Date;

/**
 *
 * @author andmi
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipalll
     */
    public telaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tipoUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataAtual = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        cadastroCliente = new javax.swing.JMenuItem();
        cadastroOS = new javax.swing.JMenuItem();
        cadastroUser = new javax.swing.JMenuItem();
        relatorio = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tech Assist v0.2 - Tela Principal");
        setBackground(new java.awt.Color(51, 51, 51));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.setToolTipText("");
        jPanel1.setMaximumSize(new java.awt.Dimension(352, 728));
        jPanel1.setMinimumSize(new java.awt.Dimension(352, 728));

        jLabel2.setBackground(new java.awt.Color(221, 221, 221));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("USUÁRIO:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setPreferredSize(new java.awt.Dimension(20, 30));

        tipoUser.setBackground(new java.awt.Color(221, 221, 221));
        tipoUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tipoUser.setText("user");
        tipoUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tipoUser.setPreferredSize(new java.awt.Dimension(20, 30));

        jLabel4.setBackground(new java.awt.Color(221, 221, 221));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("DATA:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setPreferredSize(new java.awt.Dimension(20, 30));

        dataAtual.setBackground(new java.awt.Color(221, 221, 221));
        dataAtual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dataAtual.setText("14/08/2024");
        dataAtual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dataAtual.setPreferredSize(new java.awt.Dimension(20, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/icons/iconPC.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(140, 140));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addComponent(tipoUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dataAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36)))
                .addGap(137, 137, 137))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        desktop.setMaximumSize(new java.awt.Dimension(1038, 0));
        desktop.setMinimumSize(new java.awt.Dimension(1038, 0));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(207, 40));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(207, 40));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setBackground(Color.DARK_GRAY);
        jMenuBar1.setForeground(Color.DARK_GRAY);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(207, 40));

        menuCadastro.setBackground(new java.awt.Color(51, 51, 51));
        menuCadastro.setForeground(new java.awt.Color(51, 51, 51));
        menuCadastro.setText("Cadastro");
        menuCadastro.setVerifyInputWhenFocusTarget(false);
        menuCadastro.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                menuCadastroHierarchyChanged(evt);
            }
        });

        cadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        cadastroCliente.setText("Cliente");
        cadastroCliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        cadastroCliente.setIconTextGap(-15);
        cadastroCliente.setMaximumSize(new java.awt.Dimension(120, 22));
        cadastroCliente.setMinimumSize(new java.awt.Dimension(120, 22));
        cadastroCliente.setPreferredSize(new java.awt.Dimension(120, 22));
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroCliente);

        cadastroOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        cadastroOS.setText("OS");
        cadastroOS.setIconTextGap(-15);
        cadastroOS.setMaximumSize(new java.awt.Dimension(120, 22));
        cadastroOS.setMinimumSize(new java.awt.Dimension(120, 22));
        cadastroOS.setPreferredSize(new java.awt.Dimension(120, 22));
        cadastroOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroOSActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroOS);

        cadastroUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        cadastroUser.setText("Usuários");
        cadastroUser.setIconTextGap(-15);
        cadastroUser.setMaximumSize(new java.awt.Dimension(120, 22));
        cadastroUser.setMinimumSize(new java.awt.Dimension(120, 22));
        cadastroUser.setPreferredSize(new java.awt.Dimension(120, 22));
        cadastroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroUserActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroUser);

        jMenuBar1.add(menuCadastro);

        relatorio.setBackground(new java.awt.Color(51, 51, 51));
        relatorio.setForeground(new java.awt.Color(51, 51, 51));
        relatorio.setText("Relatório");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem4.setText("Clientes");
        jMenuItem4.setIconTextGap(-15);
        jMenuItem4.setMaximumSize(new java.awt.Dimension(120, 22));
        jMenuItem4.setMinimumSize(new java.awt.Dimension(120, 22));
        jMenuItem4.setPreferredSize(new java.awt.Dimension(120, 22));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        relatorio.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem5.setText("Serviços");
        jMenuItem5.setIconTextGap(-15);
        jMenuItem5.setMaximumSize(new java.awt.Dimension(120, 22));
        jMenuItem5.setMinimumSize(new java.awt.Dimension(120, 22));
        jMenuItem5.setPreferredSize(new java.awt.Dimension(120, 22));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        relatorio.add(jMenuItem5);

        jMenuBar1.add(relatorio);

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Sobre");
        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(51, 51, 51));
        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("Sair");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroClienteActionPerformed

    private void cadastroOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroOSActionPerformed
        telaOS os = new telaOS();
        os.setVisible(true);
        try {
            os.setMaximum(true);
        } catch (PropertyVetoException e) {
        }
        desktop.add(os);
    }//GEN-LAST:event_cadastroOSActionPerformed

    private void menuCadastroHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_menuCadastroHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroHierarchyChanged

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        dataAtual.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void cadastroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroUserActionPerformed
        telaUsers us = new telaUsers();
        us.setVisible(true);
        desktop.add(us);
    }//GEN-LAST:event_cadastroUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    public JLabel getDataAtual() {
        return dataAtual;
    }

    public void setDataAtual(JLabel dataAtual) {
        this.dataAtual = dataAtual;
    }

    public JMenuItem getCadastroCliente() {
        return cadastroCliente;
    }

    public void setCadastroCliente(JMenuItem cadastroCliente) {
        this.cadastroCliente = cadastroCliente;
    }

    public JMenuItem getCadastroOS() {
        return cadastroOS;
    }

    public void setCadastroOS(JMenuItem cadastroOS) {
        this.cadastroOS = cadastroOS;
    }

    public JMenuItem getCadastroUser() {
        return cadastroUser;
    }

    public void setCadastroUser(JMenuItem cadastroUser) {
        this.cadastroUser = cadastroUser;
    }

    public JMenu getRelatorio() {
        return relatorio;
    }

    public void setRelatorio(JMenu relatorio) {
        this.relatorio = relatorio;
    }
    
    
    
    public JLabel getTipoUser() {
        return tipoUser;
    }

    public void setTipoUser(JLabel tipoUser) {
        this.tipoUser = tipoUser;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroOS;
    private javax.swing.JMenuItem cadastroUser;
    private javax.swing.JLabel dataAtual;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu relatorio;
    private javax.swing.JLabel tipoUser;
    // End of variables declaration//GEN-END:variables
}
