/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.bytecare.assistenciatecnica.turma472.telas;

import apps.controller.userController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author andmi
 */
public class telaUsers extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaUsers
     */
    public telaUsers() {
        initComponents();
    }

    userController user = new userController(this);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idUser = new javax.swing.JLabel();
        campoUserId = new javax.swing.JTextField();
        nomeUser = new javax.swing.JLabel();
        campoNomeUser = new javax.swing.JTextField();
        foneUser = new javax.swing.JLabel();
        campoFoneUser = new javax.swing.JTextField();
        senhaUser = new javax.swing.JLabel();
        campoSenhaUser = new javax.swing.JTextField();
        loginUser = new javax.swing.JLabel();
        campoLoginUser = new javax.swing.JTextField();
        perfilUser = new javax.swing.JLabel();
        campoPerfilUser = new javax.swing.JComboBox<>();
        butEditUser = new javax.swing.JButton();
        butRemoveUser = new javax.swing.JButton();
        butAddUser = new javax.swing.JButton();
        butPesquisarUser = new javax.swing.JButton();
        butLimparCampos = new javax.swing.JButton();

        setClosable(true);
        setTitle("TechAssist v0.2 - Cadastro de Usuario");
        setMinimumSize(new java.awt.Dimension(575, 410));
        setPreferredSize(new java.awt.Dimension(575, 410));

        idUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        idUser.setText("* Id");
        idUser.setPreferredSize(new java.awt.Dimension(64, 32));

        campoUserId.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoUserId.setMaximumSize(new java.awt.Dimension(50, 35));
        campoUserId.setMinimumSize(new java.awt.Dimension(50, 35));
        campoUserId.setPreferredSize(new java.awt.Dimension(50, 35));
        campoUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUserIdActionPerformed(evt);
            }
        });

        nomeUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nomeUser.setText("* Nome");
        nomeUser.setMinimumSize(new java.awt.Dimension(100, 200));
        nomeUser.setPreferredSize(new java.awt.Dimension(100, 32));

        campoNomeUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoNomeUser.setMaximumSize(new java.awt.Dimension(250, 35));
        campoNomeUser.setMinimumSize(new java.awt.Dimension(250, 35));
        campoNomeUser.setPreferredSize(new java.awt.Dimension(250, 35));
        campoNomeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeUserActionPerformed(evt);
            }
        });

        foneUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        foneUser.setText("Fone");
        foneUser.setMaximumSize(new java.awt.Dimension(100, 32));
        foneUser.setMinimumSize(new java.awt.Dimension(100, 32));
        foneUser.setName(""); // NOI18N
        foneUser.setPreferredSize(new java.awt.Dimension(100, 32));

        campoFoneUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoFoneUser.setMaximumSize(new java.awt.Dimension(150, 35));
        campoFoneUser.setMinimumSize(new java.awt.Dimension(150, 35));
        campoFoneUser.setPreferredSize(new java.awt.Dimension(150, 35));
        campoFoneUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFoneUserActionPerformed(evt);
            }
        });

        senhaUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        senhaUser.setText("* Senha");
        senhaUser.setMaximumSize(new java.awt.Dimension(100, 32));
        senhaUser.setMinimumSize(new java.awt.Dimension(100, 32));
        senhaUser.setName(""); // NOI18N
        senhaUser.setPreferredSize(new java.awt.Dimension(100, 32));

        campoSenhaUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoSenhaUser.setMaximumSize(new java.awt.Dimension(150, 35));
        campoSenhaUser.setMinimumSize(new java.awt.Dimension(150, 35));
        campoSenhaUser.setPreferredSize(new java.awt.Dimension(150, 35));
        campoSenhaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaUserActionPerformed(evt);
            }
        });

        loginUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        loginUser.setText("* Login");
        loginUser.setMaximumSize(new java.awt.Dimension(100, 32));
        loginUser.setMinimumSize(new java.awt.Dimension(100, 32));
        loginUser.setName(""); // NOI18N
        loginUser.setPreferredSize(new java.awt.Dimension(100, 32));

        campoLoginUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoLoginUser.setMaximumSize(new java.awt.Dimension(150, 35));
        campoLoginUser.setMinimumSize(new java.awt.Dimension(150, 35));
        campoLoginUser.setName(""); // NOI18N
        campoLoginUser.setPreferredSize(new java.awt.Dimension(150, 35));
        campoLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginUserActionPerformed(evt);
            }
        });

        perfilUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        perfilUser.setText("* Perfil");
        perfilUser.setMaximumSize(new java.awt.Dimension(100, 32));
        perfilUser.setMinimumSize(new java.awt.Dimension(100, 32));
        perfilUser.setName(""); // NOI18N
        perfilUser.setPreferredSize(new java.awt.Dimension(100, 32));

        campoPerfilUser.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoPerfilUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Admin" }));
        campoPerfilUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPerfilUserActionPerformed(evt);
            }
        });

        butEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/telas/iconeEditar.png"))); // NOI18N
        butEditUser.setEnabled(false);
        butEditUser.setMaximumSize(new java.awt.Dimension(70, 70));
        butEditUser.setMinimumSize(new java.awt.Dimension(70, 70));
        butEditUser.setPreferredSize(new java.awt.Dimension(70, 70));
        butEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEditUserActionPerformed(evt);
            }
        });

        butRemoveUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/telas/iconeRemover.png"))); // NOI18N
        butRemoveUser.setEnabled(false);
        butRemoveUser.setMaximumSize(new java.awt.Dimension(70, 70));
        butRemoveUser.setMinimumSize(new java.awt.Dimension(70, 70));
        butRemoveUser.setPreferredSize(new java.awt.Dimension(70, 70));
        butRemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRemoveUserActionPerformed(evt);
            }
        });

        butAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/telas/iconeAdd.png"))); // NOI18N
        butAddUser.setMaximumSize(new java.awt.Dimension(70, 70));
        butAddUser.setMinimumSize(new java.awt.Dimension(70, 70));
        butAddUser.setPreferredSize(new java.awt.Dimension(70, 70));
        butAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddUserActionPerformed(evt);
            }
        });

        butPesquisarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bytecare/assistenciatecnica/turma472/icons/iconePesquisa.png"))); // NOI18N
        butPesquisarUser.setMaximumSize(new java.awt.Dimension(70, 70));
        butPesquisarUser.setMinimumSize(new java.awt.Dimension(70, 70));
        butPesquisarUser.setPreferredSize(new java.awt.Dimension(70, 70));
        butPesquisarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPesquisarUserActionPerformed(evt);
            }
        });

        butLimparCampos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        butLimparCampos.setText("Limpar Campos");
        butLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoLoginUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPerfilUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(foneUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(senhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(campoFoneUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(butLimparCampos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(butAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butPesquisarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foneUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFoneUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butLimparCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(butEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butPesquisarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeUserActionPerformed

    private void campoFoneUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFoneUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFoneUserActionPerformed

    private void campoSenhaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaUserActionPerformed

    private void campoLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginUserActionPerformed

    private void campoPerfilUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPerfilUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPerfilUserActionPerformed

    private void campoUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUserIdActionPerformed

    private void butAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddUserActionPerformed
        try {
            user.addUser();
        } catch (SQLException ex) {
            Logger.getLogger(telaUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butAddUserActionPerformed

    private void butEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEditUserActionPerformed
        try {
            user.editUser();
        } catch (SQLException ex) {
            Logger.getLogger(telaUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butEditUserActionPerformed

    private void butRemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRemoveUserActionPerformed
        user.removeUser();
    }//GEN-LAST:event_butRemoveUserActionPerformed

    private void butPesquisarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPesquisarUserActionPerformed
        try {
            user.pesquisarUser();
        } catch (SQLException ex) {
            Logger.getLogger(telaUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butPesquisarUserActionPerformed

    private void butLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimparCamposActionPerformed
        user.limparCampos();
        butAddUser.setEnabled(true);
        butPesquisarUser.setEnabled(true);
    }//GEN-LAST:event_butLimparCamposActionPerformed

    public JButton getButAddUser() {
        return butAddUser;
    }

    public void setButAddUser(JButton addUser) {
        this.butAddUser = addUser;
    }

    public JTextField getCampoFoneUser() {
        return campoFoneUser;
    }

    public void setCampoFoneUser(JTextField campoFoneUser) {
        this.campoFoneUser = campoFoneUser;
    }

    public JTextField getCampoLoginUser() {
        return campoLoginUser;
    }

    public void setCampoLoginUser(JTextField campoLoginUser) {
        this.campoLoginUser = campoLoginUser;
    }

    public JTextField getCampoNomeUser() {
        return campoNomeUser;
    }

    public void setCampoNomeUser(JTextField campoNomeUser) {
        this.campoNomeUser = campoNomeUser;
    }

    public JComboBox<String> getCampoPerfilUser() {
        return campoPerfilUser;
    }

    public void setCampoPerfilUser(JComboBox<String> campoPerfilUser) {
        this.campoPerfilUser = campoPerfilUser;
    }

    public JTextField getCampoSenhaUser() {
        return campoSenhaUser;
    }

    public void setCampoSenhaUser(JTextField campoSenhaUser) {
        this.campoSenhaUser = campoSenhaUser;
    }

    public JButton getButEditUser() {
        return butEditUser;
    }

    public void setButEditUser(JButton editUser) {
        this.butEditUser = editUser;
    }

    public JButton getButRemoveUser() {
        return butRemoveUser;
    }

    public void setButRemoveUser(JButton removeUser) {
        this.butRemoveUser = removeUser;
    }

    public JTextField getCampoUserId() {
        return campoUserId;
    }

    public void setCampoUserId(JTextField campoUserId) {
        this.campoUserId = campoUserId;
    }

    public JButton getButPesquisarUser() {
        return butPesquisarUser;
    }

    public void setButPesquisarUser(JButton pesquisarUser) {
        this.butPesquisarUser = pesquisarUser;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAddUser;
    private javax.swing.JButton butEditUser;
    private javax.swing.JButton butLimparCampos;
    private javax.swing.JButton butPesquisarUser;
    private javax.swing.JButton butRemoveUser;
    private javax.swing.JTextField campoFoneUser;
    private javax.swing.JTextField campoLoginUser;
    private javax.swing.JTextField campoNomeUser;
    private javax.swing.JComboBox<String> campoPerfilUser;
    private javax.swing.JTextField campoSenhaUser;
    private javax.swing.JTextField campoUserId;
    private javax.swing.JLabel foneUser;
    private javax.swing.JLabel idUser;
    private javax.swing.JLabel loginUser;
    private javax.swing.JLabel nomeUser;
    private javax.swing.JLabel perfilUser;
    private javax.swing.JLabel senhaUser;
    // End of variables declaration//GEN-END:variables
}
